### ISSUE TITLE
Not working with multi domain settings

### ISSUE THREAD

**Issue by madeus** [pulsejet/banner-warn#5]
How to set up configuration options for multiple domains? I tried as an array list but it doesn't work. Can you tell how to set this plugin for several domains?

```php
$config['org_email_regex'] = array('/@(.*\.|)domain1\.ab\.pl/i','/@(.*\.|)domain2\.ab\.pl/i');
 ```
This setting does not work. There is an error in the logs:

```
PHP Warning:  preg_match() expects parameter 1 to be string, array given in /path_to_roundcube/plugins/banner_warn/banner_warn.php on line 137
```

**Comment by pulsejet** [comment]
Use regex or
```php
$config['org_email_regex'] = "/@(.*\.|)(domain1|domain2)\.ab\.pl/i";
```

**Comment by madeus** [comment]
Thx, it's working now like a charm.

**Comment by AlexBeakes** [comment]
My config dosn't want to work(((
`$config['org_email_regex'] = "/@(.*\.|)(example1|example2|example3)\.com\.net\.xyz/i";`
Is there anything that can go wrong?
How to implement more domains?

**Comment by pulsejet** [comment]
@AlexBeakes your regex is wrong. It will match only `@example1.com.net.xyz` and similar. Use https://regex101.com/
